import { IncomingDocument } from './types';

export const initialDocuments: IncomingDocument[] = [
  {
    id: '1',
    documentNumber: '123/UBND-VP',
    issueDate: '2023-10-25',
    issuingAgency: 'UBND Tỉnh',
    summary: 'V/v báo cáo tình hình kinh tế xã hội tháng 10',
    directives: 'Yêu cầu các đơn vị khẩn trương báo cáo số liệu trước ngày 30/10.',
    executingUnit: 'Phòng Kế hoạch - Tài chính',
    assignee: 'Nguyễn Văn A',
    executionDate: '',
    deadline: '2023-10-30',
    progress: 'Đang xử lý',
    advisingDocNumber: '',
    leaderOpinion: 'Giao anh A bám sát tiến độ, báo cáo trước 28/10.',
    archived: false,
  },
  {
    id: '2',
    documentNumber: '45/STNMT-MT',
    issueDate: '2023-10-26',
    issuingAgency: 'Sở Tài nguyên và Môi trường',
    summary: 'Thanh tra công tác bảo vệ môi trường khu công nghiệp',
    directives: 'Chuẩn bị hồ sơ đón đoàn thanh tra.',
    executingUnit: 'Phòng Tài nguyên - Môi trường',
    assignee: 'Trần Thị B',
    executionDate: '2023-11-05',
    deadline: '2023-11-05',
    progress: 'Chưa thực hiện',
    advisingDocNumber: '',
    leaderOpinion: '',
    archived: false,
  },
  {
    id: '3',
    documentNumber: '88/TB-UBND',
    issueDate: '2023-10-20',
    issuingAgency: 'UBND Huyện',
    summary: 'Thông báo kết luận cuộc họp giao ban thường kỳ',
    directives: 'Các bộ phận thực hiện nghiêm túc kết luận cuộc họp.',
    executingUnit: 'Văn phòng HĐND - UBND',
    assignee: 'Lê Văn C',
    executionDate: '2023-10-22',
    deadline: '2023-10-24',
    progress: 'Đã hoàn thành',
    advisingDocNumber: '45/BC-VP',
    leaderOpinion: 'Đã xem báo cáo.',
    archived: true,
  }
];
